import numpy as np
import pandas as pd
import scipy.stats as stats
from final.simulate_model import simulate_moments


def get_simulation_distribution(n_simulations, master_seed, **kwargs):

    """
    Run the simulation many times to capture stochastic variability.

    Uses a seed-scheduling scheme to ensure 100% replicability: a single
    master seed deterministically generates one child seed per run, so the
    full distribution can be reproduced exactly from ``master_seed`` alone.

    Args:
        n_simulations (int): Number of Monte Carlo draws (simulation runs).
        master_seed (int): Root seed for the master RNG. Controls the entire
            seed schedule; fix this value to get identical results across runs.
        **kwargs: Additional keyword arguments forwarded verbatim to
            ``simulate_moments`` on every iteration (e.g. ``params``,
            ``model``, ``age_grid``, ``n_agents``).

    Returns:
        pd.DataFrame: A DataFrame with ``n_simulations`` rows, one per run.
            Each column corresponds to a moment returned by
            ``simulate_moments``.

    """

    master_rng = np.random.default_rng(master_seed)
    seed_array = master_rng.integers(low=1, high=100_000, size=n_simulations)

    all_sims = []
    
    for i in range(n_simulations):
        # Es vital que NO fijes la semilla (seed) dentro de simulate_moments
        # para que cada iteración tenga shocks distintos.
        res = simulate_moments(seed=seed_array[i], **kwargs)
        all_sims.append(res)
        
    # Devolvemos un DataFrame donde cada fila es una simulación
    return pd.DataFrame(all_sims)

def dataframe_results(
        n_simulations,
        master_seed,
        params,
        model,
        params_base,
        age_grid,
        n_agents,
        results_paper,
):
    """
    Compare simulated moments against published paper results.

    Args:
        n_simulations (int): Number of Monte Carlo draws passed to
            :func:`get_simulation_distribution`.
        master_seed (int): Root seed for reproducibility; see
            :func:`get_simulation_distribution`.
        params (dict | array-like): Model parameters for the current
            calibration.
        model: Model generated by PyLCM.
        params_base (dict | array-like): Baseline parameter values used
            inside the simulation generated with PyLCM.
        age_grid (array-like): Grid of age values over which the model
            is solved or simulated.
        n_agents (int): Number of agents per simulation run.
        results_paper (pd.Series | dict): Result moments from the paper.

    Returns:
        pd.DataFrame: A comparison table indexed by moment name with columns:

        - **Own Simulation** – mean of the simulated moment across all runs.
        - **Paper Simulation** – target value from ``results_paper``.
        - **Std. Error** – standard deviation of the simulated moment.
        - **t-Statistic** – z-score of the difference
          ``(mean − paper) / std``.
        - **p-Value** – two-sided p-value under a standard normal
          approximation.
    """

    sim_dist = get_simulation_distribution(
        n_simulations=n_simulations,
        master_seed=master_seed,
        params=params,
        model=model,
        params_base=params_base,
        age_grid=age_grid,
        n_agents=n_agents
    )

    sim_mean = sim_dist.mean()
    sim_sd = sim_dist.std()

    t_stats = (sim_mean - results_paper) / sim_sd

    comparison_with_paper = pd.DataFrame({
        "Own Simulation": sim_mean,
        "Paper Simulation": results_paper,
        "Std. Error": sim_sd,
        "t-Statistic": t_stats,
        "p-Value": 2 * (1 - stats.norm.cdf(np.abs(t_stats)))
    })
    return comparison_with_paper